name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; else pip install pytest hypothesis pytest-cov; fi

      - name: Run tests with coverage
        env:
          PYTHONPATH: packages
        run: |
          pytest -v --tb=short --cov=packages --cov-report=term-missing --cov-fail-under=80

