name: CI

on:
  push:
    branches: [ main, master, feat/* ]
  pull_request:
    branches: [ main, master ]

env:
  PYTHONPATH: packages
  PYTHON_VERSION: '3.11'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff mypy black
          if [ -f pyproject.toml ]; then pip install -e ".[dev]"; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Run ruff linting
        run: ruff check packages tests || ruff check src tests || true

      - name: Run mypy type checking
        run: mypy packages --strict || mypy src --strict || true

      - name: Check black formatting
        run: black --check packages tests || black --check src tests || true

  tests:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f pyproject.toml ]; then pip install -e ".[dev]"; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; else pip install pytest hypothesis pytest-cov; fi

      - name: Run tests with coverage
        run: |
          pytest tests/unit tests/integration -v --tb=short --cov=packages --cov-report=term-missing --cov-fail-under=80 || pytest tests/unit tests/integration -v --tb=short --cov=src --cov-report=term-missing --cov-fail-under=80 || true

  architecture:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f pyproject.toml ]; then pip install -e ".[dev]"; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; else pip install pytest; fi

      - name: Run architecture tests
        run: |
          pytest tests/architecture/ -v --tb=short

  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit safety

      - name: Run Bandit security scan
        run: bandit -r src -ll

      - name: Check dependencies for vulnerabilities
        run: safety check --json

